version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "http://s3-us-east-2.amazonaws.com/altrusight-build"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
        - appspec.yml
    base-directory: 'dist*'
    discard-paths: yes
